ALTER TABLE orders ADD COLUMN delivery_full_name VARCHAR(255) NOT NULL;
ALTER TABLE orders ADD COLUMN delivery_phone VARCHAR(20) NOT NULL;
ALTER TABLE orders ADD COLUMN delivery_line1 VARCHAR(255) NOT NULL;
ALTER TABLE orders ADD COLUMN delivery_line2 VARCHAR(255);
ALTER TABLE orders ADD COLUMN delivery_city VARCHAR(100) NOT NULL;
ALTER TABLE orders ADD COLUMN delivery_state VARCHAR(100) NOT NULL;
ALTER TABLE orders ADD COLUMN delivery_pin_code VARCHAR(20) NOT NULL;
ALTER TABLE orders ADD COLUMN delivery_country VARCHAR(100) NOT NULL;
